language: node_js

node_js:
  - 12

services:
  - docker

before_install:
  - docker-compose up -d --build
  
deploy:
  skip_cleanup: true
  provider: heroku
  api_key: 80c72ceb-c0c5-467c-82f0-7a6f1640df22
  app: otus-graphql
  on:
    branch: develop
