language: node_js

node_js:
  - 12

services:
  - docker

env:
  COMPOSE_VERSION: 1.4.1

before_install:
 - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
 - chmod +x docker-compose
 - sudo mv docker-compose /usr/local/bin

script:
  - docker-compose up -d --build
  
deploy:
  skip_cleanup: true
  provider: heroku
  api_key: 80c72ceb-c0c5-467c-82f0-7a6f1640df22
  app: otus-graphql
  on:
    branch: develop
