version: '3.1'

services:
  db:
    image: postgres:12.2
    restart: always
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: otus-node
    ports:
      - 5433:5432
  node_proj_docker:
    build: .
    ports:
      - "3000:3000"
    environment:
      DB_HOST: host.docker.internal